server:
  port: 8030

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

  redis:
    host: 47.111.154.43
    port: 6377
    database: 0
    password: baoyun
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 2000ms

  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  activiti:
    database-schema-update: true
    check-process-definitions: false  #这个比较重要，不配置的话会扫描类路径下的processes下的.xml文件
    process-definition-location-prefix: classpath:/processes/

#mybatis 配置
mybatis:
  type-aliases-package: com.test.activiti.entity
mybatis-plus:
  mapper-locations: classpath:mappings/*.xml
  global-config.db-config.id-type: id_worker_str
  global-config.db-config.db-type: mysql